# Generated by Django 3.2.3 on 2021-06-09 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rmf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('upload_completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('version', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('benchmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='stigs.benchmark')),
                ('parent_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='stigs.group')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('benchmark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='stigs.benchmark')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('operator', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('boolean', 'boolean'), ('number', 'number'), ('string', 'string')], max_length=20)),
                ('benchmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='stigs.benchmark')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='stigs.group')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValueValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(max_length=255, null=True)),
                ('value_text', models.TextField()),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_values', to='stigs.value')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(db_index=True, max_length=255)),
                ('version', models.CharField(max_length=100, null=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=10)),
                ('benchmark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='stigs.benchmark')),
                ('ccis', models.ManyToManyField(related_name='rules', to='rmf.ControlCorrelationIdentifier')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='stigs.group')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileSelects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idref', models.CharField(max_length=100)),
                ('selected', models.BooleanField(default=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selects', to='stigs.group')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selects', to='stigs.profile')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selects', to='stigs.rule')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FixText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixref', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fix_texts', to='stigs.rule')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixes', to='stigs.rule')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=255)),
                ('check_content', models.TextField(blank=True, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='stigs.rule')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BenchmarkPlainText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('text', models.TextField(null=True)),
                ('benchmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plain_texts', to='stigs.benchmark')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
    ]
