# Generated by Django 3.2.3 on 2021-06-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stigs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benchmark',
            name='upload_completed',
        ),
        migrations.AddField(
            model_name='benchmark',
            name='source',
            field=models.CharField(choices=[('DISA', 'DISA'), ('CS2', 'CS2')], default='DISA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benchmark',
            name='upload_status',
            field=models.CharField(choices=[('Uploading', 'U'), ('Completed', 'C'), ('Error', 'E')], default='U', max_length=20),
        ),
    ]
