# Generated by Django 3.2.3 on 2021-06-11 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stigs', '0002_auto_20210611_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='CS2Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs2_id', models.IntegerField()),
                ('cs2_title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('system', models.CharField(blank=True, max_length=500, null=True)),
                ('cs2_tags', models.ManyToManyField(related_name='cs2_info', to='stigs.CS2Tag')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idents', to='stigs.rule')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
    ]
