# Generated by Django 3.2.3 on 2021-06-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stigs', '0003_cs2tag_ident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ident',
            name='cs2_tags',
        ),
        migrations.AddField(
            model_name='ident',
            name='cs2_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ident',
            name='cs2_title',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='CS2Tag',
        ),
    ]
