# Generated by Django 3.2.3 on 2021-06-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stigs', '0004_auto_20210611_1836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ident',
        ),
    ]
