# Generated by Django 3.2.3 on 2021-06-08 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NistControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_type', models.CharField(max_length=20)),
                ('baseline', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('number', models.CharField(db_index=True, max_length=20)),
                ('family', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=250, null=True)),
                ('revision', models.IntegerField()),
                ('privacy_impact', models.CharField(blank=True, max_length=5, null=True)),
                ('priority', models.CharField(blank=True, choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], max_length=20, null=True)),
                ('parent_control', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enhancements', to='rmf.nistcontrol')),
            ],
        ),
        migrations.CreateModel(
            name='NistRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NistSupplementGuidanceRelatedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NistSupplementalGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('control', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplemental_guidance', to='rmf.nistcontrol')),
                ('related', models.ManyToManyField(related_name='related_items', to='rmf.NistSupplementGuidanceRelatedItems')),
            ],
        ),
        migrations.CreateModel(
            name='NistStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=25, null=True)),
                ('description', models.TextField(null=True)),
                ('control', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statement', to='rmf.nistcontrol')),
                ('parent_control', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_statements', to='rmf.nistcontrol')),
                ('statement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='rmf.niststatement')),
            ],
        ),
        migrations.CreateModel(
            name='NistReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.TextField(null=True)),
                ('text', models.TextField(null=True)),
                ('short_name', models.TextField(null=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='rmf.nistcontrol')),
            ],
        ),
        migrations.CreateModel(
            name='NistDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('control', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='rmf.nistcontrol')),
            ],
        ),
        migrations.AddField(
            model_name='nistcontrol',
            name='related',
            field=models.ManyToManyField(related_name='related_controls', to='rmf.NistRelated'),
        ),
        migrations.CreateModel(
            name='ControlCorrelationIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True, unique=True)),
                ('contributor', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('parameter', models.CharField(blank=True, max_length=255, null=True)),
                ('publishdate', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('implementation_guidance', models.TextField(blank=True, null=True)),
                ('assessment_procedures', models.TextField(blank=True, null=True)),
                ('controls', models.ManyToManyField(related_name='ccis', to='rmf.NistControl')),
                ('statements', models.ManyToManyField(related_name='ccis', to='rmf.NistStatement')),
            ],
        ),
    ]
